### ISSUE TITLE
Mount a folder to docker container

### ISSUE THREAD

**Issue by NeroCube** [NeroCube/bookmark#215]
```
services:
  api:
    restart: always
    build: ./api
    volumes:
      - ./api:/home/project/app
    ports:
      - "7000:7000"
    command: gunicorn -t 3000 -w 1 -b :7000 app:app
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - api
```
1.  Remove old docker container.
- `docker stop $(docker ps -a -q)`
- `docker rm $(docker ps -a -q)`
2. Add Volumes  as below.
```
volumes:
      - ./api:/home/project/app
```
3. Restart docker container.
-  `docker-compose up --d`
